services:
  # Utility service for running composer commands. Useful for adding tools from packagist
  # Image from: https://hub.docker.com/_/composer
  composer:
    image: composer:2.1.6
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      COMPOSER_HOME: /.composer
    volumes:
      - ./:/app
      - ~/.composer:/.composer
    command: install

  test:
    build: .
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: []
    command: vendor/bin/phpunit
